name: Android CI (Shelter Fork)

on:
  push:
    branches:
      - main # Or your default branch, e.g., master, develop
  pull_request:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 (or desired version)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Or 'zulu', 'adopt'
          java-version: '17' # Adjust to the Java version required by your project

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug # Or 'assembleRelease', 'bundleRelease' depending on your build target

      - name: Upload APKs (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: app/build/outputs/apk/debug/ # Adjust this path if your build output differs (e.g., release)

