name: Build Shelter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Fix versionCode and versionName
        run: |
          sed -i 's/versionCode\s*-1/versionCode 1/' app/build.gradle
          sed -i 's/versionName\s*getGitVersionName()/versionName "1.0"/' app/build.gradle

      - name: Build APK
        run: ./gradlew assembleRelease -PabiFilters=armeabi-v7a

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: shelter-armeabi-v7a
          path: app/build/outputs/apk/release/*.apk

